# Generated by Django 4.1 on 2022-11-18 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=20)),
                ('nombre', models.TextField(max_length=50)),
                ('apellidos', models.TextField(max_length=50)),
                ('sexo', models.TextField(max_length=50)),
                ('curso', models.TextField(max_length=50)),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)])),
                ('ciudad', models.TextField(max_length=50)),
                ('comnuna', models.TextField(max_length=50)),
            ],
        ),
    ]
