# Generated by Django 4.1.3 on 2022-11-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('apePaterno', models.TextField(max_length=50)),
                ('apeMaterno', models.TextField(max_length=50)),
                ('sexo', models.TextField(max_length=50)),
                ('curso', models.TextField(max_length=50)),
                ('contacto', models.IntegerField()),
                ('ciudad', models.TextField(max_length=50)),
                ('comnuna', models.TextField(max_length=50)),
            ],
        ),
    ]
