# Generated by Django 4.1.3 on 2022-11-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_colegio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='contacto',
            new_name='eddad',
        ),
    ]
