# Generated by Django 4.1 on 2022-11-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_colegio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='comnuna',
            new_name='comuna',
        ),
    ]
