# Generated by Django 4.1.3 on 2022-11-18 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_colegio', '0003_rename_eddad_alumnos_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
